;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Aug 3 2021
; Processor: 80C31
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================
LED1		BIT		P1.0
LED2		BIT		P1.1
LED3		BIT		P1.2
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      ;org   0000h
      ;jmp   Start

;====================================================================
; CODE SEGMENT
;====================================================================

      ;org   0100h
org        0000H
LOOP:	SETB LED1
	CLR LED2
	CLR LED3
	ACALL DELAY2
	SETB LED3
	SETB LED2
	CLR LED1
	ACALL DELAY
        SJMP LOOP
	
DELAY:   MOV R1,#255
WAIT1: 	MOV R2, #4
WAIT2: 	MOV R3,#255
	       DJNZ R3,$
	       DJNZ R2,WAIT2
	       DJNZ R1,WAIT1
	       RET
	       
DELAY2: 
	       MOV R7, #10D
WAIT3:    MOV TMOD, #10H
		MOV TL1,#57H
		MOV TH1, #4CH
		SETB TR1
BACK: JNB TF1,BACK
	       CLR TR1
	       CLR TF1
	       DJNZ R7, WAIT3
	       RET
   
END
;====================================================================
;END
